#------------------------------------------------------------------------------
# usage: Use tutor to enable the Open edX Notes service plugin
#------------------------------------------------------------------------------
name: Open edX Tutor k8s enable Notes plugin
description: Github Action to install and enable the Tutor plugin - Open edX Notes service
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  namespace:
    description: 'The Kubernetes namesapce to which the Open edX platform environment will be deployed. Example: openedx-prod'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    # retrieve the MySQL connection parameters that we created in Terraform
    # and then stored in Kubernetes secrets. These include:
    #   MYSQL_HOST: mysql.app.yourdomain.com
    #   MYSQL_PORT: "3306"
    #   NOTES_MYSQL_USERNAME: openedx
    #   NOTES_MYSQL_PASSWORD: **************
    #   MYSQL_ROOT_USERNAME: root
    #   MYSQL_ROOT_PASSWORD: *************
    - name: fetch MySQL configuration from Kubernetes secrets
      id: get-secret
      uses: openedx-actions/tutor-k8s-get-secret@v1.0.0
      with:
        eks-namespace: ${{ inputs.namespace }}
        eks-secret-name: mysql-notes

    # mcdaniel nov-2022
    # see: https://github.com/overhangio/tutor-notes
    # The plugin is currently bundled with the binary releases of Tutor.
    # It's only necessary to pip install if you have installed Tutor from source.
    #
    # However, since we pip install tutor we apparently *ARE* installing tutor from source.
    #------------------------------------------------------
    - name: install Notes plugin
      id: install-notes
      shell: bash
      run: pip install tutor-notes

    - name: Enable the Notes plugin
      id: config-save
      run: |-
        tutor plugins enable notes
        tutor config save
      shell: bash
